apiVersion: v2
appVersion: "1.0"
description: ?
name: jenkins
type: application
version: 0.1.0
dependencies:
  - name: jenkinsci/jenkins
    version: "3.3.11"
    repository: https://charts.jenkins.io
